services:
  - type: web
    name: sng-ocr-service
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8000"
      - key: RAILS_API_URL
        value: "https://hairsearcherapp.onrender.com"
